name: Install dependencies
description: 'Installs and caches the dependencies'

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: 'actions/checkout@v2'

    - name: Use Node.js 18.x
      uses: 'actions/setup-node@v2'
      with:
        node-version: '18.x'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ hashFiles('./package.json') }}

    - name: Install required dependencies on yarn.lock change
      if: steps.cache-npm.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile
