name: Pull request workflow

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-dependencies

    - name: Lint
      run: yarn lint

    - name: Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ secrets.BASE_URL }}
        ENV: ${{ secrets.ENV }}
      run: yarn test
