name: Pull request workflow

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/install-dependencies

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test
