name: Pull request workflow

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'
        
    - name: Install
      run: yarn install --immutable
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
